/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bhrcsbtylvysoeuyaauz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJocmNzYnR5bHZ5c29ldXlhYXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxNjM4MTIsImV4cCI6MjA3OTczOTgxMn0._-jeSwJ9fY9tUTL0ZtYikbQScSPRC0G0-mzJT3noH_s"